### ISSUE TITLE
File not fully encrypting

### ISSUE THREAD

**Issue by UnbihexiumFan** [xBZZZZ/gdccdated#2]
When I'm trying to decrypt my files, I'll still see big blocks of text that are still encrypted.

[CCLocalLevels (4).txt](https://github.com/xBZZZZ/gdccdated/files/12095464/CCLocalLevels.4.txt)

Is this possibly an issue with the file size, or a problem with the program?

EDIT: I deleted all of my levels except 1, and it still won't work. Is the problem that it wasn't designed to encrypt fully fixed CCLocalLevels.dat files? Also deleted excerpt and replaced it with the actual file.

**Comment by xBZZZZ** [comment]
the file you attached is decrypted

I found this sentence in email I got:
> Here's an excerpt from my CCLocalLevels.dat file: `<s>H4sIAAAAAAAAC-1`

`H4sIAAAAAAAAC-1`&hellip; is gzip + urlsafe base64 encoded level data

gdccdated doesn't recursively look for levels and auto-decode level data when loading CC*.dat file

but there is string editor for decoding level data:
![string editor screenshot](https://github.com/xBZZZZ/gdccdated/assets/91378413/a9672b06-c723-4d49-b23d-618d6c56ef6a)
